"""
Leomail v3 — Template Engine
Variable substitution only. Each template is already unique (generated by external AI software).
"""
import re
from loguru import logger


# Variables we support
# {{USER}} is alias for {{EMAILNAME}} (part before @ in recipient email)
SUPPORTED_VARIABLES = ["LINK", "FIRSTNAME", "LASTNAME", "EMAILNAME", "USER"]


def detect_variables(text: str) -> list[str]:
    """Detect which template variables are used in text."""
    found = []
    upper_text = text.upper()
    for var in SUPPORTED_VARIABLES:
        if "{{" + var + "}}" in upper_text:
            found.append(var)
    return found


def render_template(
    subject: str,
    body: str,
    recipient: dict,
    link_url: str = "",
) -> tuple[str, str]:
    """
    Render a template for a specific recipient.
    Only substitutes variables — no spintax, no uniqueness markers.
    Each template is already unique (generated by external AI software).
    
    Args:
        subject: Template subject (plain text with {{VAR}} variables)
        body: Template body (plain text with {{VAR}} variables)
        recipient: dict with keys: email, first_name, last_name
        link_url: URL to substitute for {{LINK}}
    
    Returns:
        (rendered_subject, rendered_body)
    """
    email = recipient.get("email", "")
    first_name = recipient.get("first_name", "")
    last_name = recipient.get("last_name", "")
    email_name = email.split("@")[0] if "@" in email else email

    # Variable substitution (case-insensitive)
    replacements = {
        "{{LINK}}": link_url,
        "{{FIRSTNAME}}": first_name,
        "{{LASTNAME}}": last_name,
        "{{EMAILNAME}}": email_name,
        "{{USER}}": email_name,
    }

    rendered_subject = subject
    rendered_body = body

    for var, value in replacements.items():
        # Case-insensitive replace
        rendered_subject = re.sub(re.escape(var), value, rendered_subject, flags=re.IGNORECASE)
        rendered_body = re.sub(re.escape(var), value, rendered_body, flags=re.IGNORECASE)

    return rendered_subject, rendered_body


def render_preview(subject: str, body: str) -> tuple[str, str]:
    """Render a preview with example data (for frontend display)."""
    example_recipient = {
        "email": "john.doe@gmail.com",
        "first_name": "John",
        "last_name": "Doe",
    }
    return render_template(
        subject, body,
        recipient=example_recipient,
        link_url="https://example.com/offer",
    )
